joy_teleop:
  ros__parameters:
    teleop:
      type: topic
      interface_type: geometry_msgs/msg/TwistStamped
      topic_name: /base_controller/cmd_vel
      deadman_buttons: [9] # L1; set to an invalid number like 99 to disable
      axis_mappings:
        twist-linear-x:
          axis: 1 # Left stick vertical
          scale: 0.13
          offset: 0.0
        twist-linear-y:
          axis: 0 # Left stick horizontal
          scale: 0.11
          offset: 0.0
        twist-angular-z:
          axis: 2 # Right stick horizontal
          scale: 0.44
          offset: 0.0
        header-frame_id:
          value: 'base_link'

    estop_enable:
      type: service
      interface_type: std_srvs/srv/SetBool
      service_name: /emergency_stop
      service_request:
        data: true
      buttons: [0]  # A = enable

    estop_disable:
      type: service
      interface_type: std_srvs/srv/SetBool
      service_name: /emergency_stop
      service_request:
        data: false
      buttons: [1]  # B = disable
